include: package:effective_dart/analysis_options.yaml

analyzer:
  errors:
    undefined_prefixed_name: ignore

linter:
  rules:
    public_member_api_docs: false
    avoid_classes_with_only_static_members: false
    unnecessary_lambdas: false
    directives_ordering: false
    library_names: true
    file_names: true
tesrttert

hjghfju
прап